---
snmp:
  oids:
    cdpCacheDeviceId: '.1.3.6.1.4.1.9.9.23.1.2.1.1.6'
    cdpCacheDevicePort: '.1.3.6.1.4.1.9.9.23.1.2.1.1.7'
    cdpCachePlatform: '.1.3.6.1.4.1.9.9.23.1.2.1.1.8'
    cdpCacheAddress: '.1.3.6.1.4.1.9.9.23.1.2.1.1.4'
    hostname: '.1.3.6.1.2.1.1.5.0'
    ifDescription: '.1.3.6.1.2.1.2.2.1.2' 
  communities:
    - "secret"
    - "public"
    - "private"
...